In [1]:
import pandas as pd
dtset = pd.read_csv("Placement.csv")
dtset = dtset.drop(columns=['sl_no'])
dtset

,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [2]:
dtset.isnull().sum()

gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

In [3]:
# Quantitative columns
quan = dtset.select_dtypes(include=['number']).columns

# Qualitative columns
qual = dtset.select_dtypes(include=['object', 'category']).columns

dtset[quan]

     ssc_p  hsc_p  degree_p  etest_p  mba_p    salary
0    67.00  91.00     58.00     55.0  58.80  270000.0
1    79.33  78.33     77.48     86.5  66.28  200000.0
2    65.00  68.00     64.00     75.0  57.80  250000.0
3    56.00  52.00     52.00     66.0  59.43       NaN
4    85.80  73.60     73.30     96.8  55.50  425000.0
..     ...    ...       ...      ...    ...       ...
210  80.60  82.00     77.60     91.0  74.49  400000.0
211  58.00  60.00     72.00     74.0  53.62  275000.0
212  67.00  67.00     73.00     59.0  69.72  295000.0
213  74.00  66.00     58.00     70.0  60.23  204000.0
214  62.00  58.00     53.00     89.0  60.22       NaN

[215 rows x 6 columns]

In [9]:
import numpy as np
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy = 'mean')
imp.fit(dtset[quan])
df = imp.transform(dtset[quan])
df = pd.DataFrame(df, columns = quan)
df

     ssc_p  hsc_p  degree_p  etest_p  mba_p         salary
0    67.00  91.00     58.00     55.0  58.80  270000.000000
1    79.33  78.33     77.48     86.5  66.28  200000.000000
2    65.00  68.00     64.00     75.0  57.80  250000.000000
3    56.00  52.00     52.00     66.0  59.43  288655.405405
4    85.80  73.60     73.30     96.8  55.50  425000.000000
..     ...    ...       ...      ...    ...            ...
210  80.60  82.00     77.60     91.0  74.49  400000.000000
211  58.00  60.00     72.00     74.0  53.62  275000.000000
212  67.00  67.00     73.00     59.0  69.72  295000.000000
213  74.00  66.00     58.00     70.0  60.23  204000.000000
214  62.00  58.00     53.00     89.0  60.22  288655.405405

[215 rows x 6 columns]

In [11]:
catset = dtset[qual]
catset

,gender,ssc_b,hsc_b,hsc_s,degree_t,workex,specialisation,status
0,M,Others,Others,Commerce,Sci&Tech,No,Mkt&HR,Placed
1,M,Central,Others,Science,Sci&Tech,Yes,Mkt&Fin,Placed
2,M,Central,Central,Arts,Comm&Mgmt,No,Mkt&Fin,Placed
3,M,Central,Central,Science,Sci&Tech,No,Mkt&HR,Not Placed
4,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
...,...,...,...,...,...,...,...,...
210,M,Others,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
211,M,Others,Others,Science,Sci&Tech,No,Mkt&Fin,Placed
212,M,Others,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
213,F,Others,Others,Commerce,Comm&Mgmt,No,Mkt&HR,Placed
214,M,Central,Others,Science,Comm&Mgmt,No,Mkt&HR,Not Placed

In [14]:
mergeset = [df,catset]
preprocessed = pd.concat(mergeset, axis = 1)
preprocessed

,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary,gender,ssc_b,hsc_b,hsc_s,degree_t,workex,specialisation,status
0,67.00,91.00,58.00,55.0,58.80,270000.000000,M,Others,Others,Commerce,Sci&Tech,No,Mkt&HR,Placed
1,79.33,78.33,77.48,86.5,66.28,200000.000000,M,Central,Others,Science,Sci&Tech,Yes,Mkt&Fin,Placed
2,65.00,68.00,64.00,75.0,57.80,250000.000000,M,Central,Central,Arts,Comm&Mgmt,No,Mkt&Fin,Placed
3,56.00,52.00,52.00,66.0,59.43,288655.405405,M,Central,Central,Science,Sci&Tech,No,Mkt&HR,Not Placed
4,85.80,73.60,73.30,96.8,55.50,425000.000000,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,80.60,82.00,77.60,91.0,74.49,400000.000000,M,Others,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
211,58.00,60.00,72.00,74.0,53.62,275000.000000,M,Others,Others,Science,Sci&Tech,No,Mkt&Fin,Placed
212,67.00,67.00,73.00,59.0,69.72,295000.000000,M,Others,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
213,74.00,66.00,58.00,70.0,60.23,204000.000000,F,Others,Others,Commerce,Comm&Mgmt,No,Mkt&HR,Placed
214,62.00,58.00,53.00,89.0,60.22,288655.405405,M,Central,Others,Science,Comm&Mgmt,No,Mkt&HR,Not Placed

In [15]:
preprocessed.isnull().sum()

ssc_p             0
hsc_p             0
degree_p          0
etest_p           0
mba_p             0
salary            0
gender            0
ssc_b             0
hsc_b             0
hsc_s             0
degree_t          0
workex            0
specialisation    0
status            0
dtype: int64

In [17]:
preprocessed.to_csv("processedPlacementData.csv", index=False)